// crates/ajax-web/web/src/features/task/NewTaskSheet.tsx
import { useEffect, useRef, useState, type FormEvent, type MouseEvent } from "react";
import type { BrowserCockpitView, RepoSummary } from "@/shared/lib/types";
import { requestId, startTask } from "@/shared/lib/api";
import { startTaskHandle } from "./taskSlug";
import { useSheetDrag } from "@/shared/hooks/useSheetDrag";
import FullscreenLayer from "@/shared/ui/FullscreenLayer";
import { Button } from "@/shared/ui/button";
import { Sheet, SheetContent, SheetTitle } from "@/shared/ui/sheet";

interface Props {
  repos: RepoSummary[];
  selectedProject?: string | null;
  onClose?: () => void;
  onCockpit?: (cockpit: BrowserCockpitView) => void;
  onResult?: (message: string, output: string | null | undefined, isError: boolean) => void;
  onOpenTask?: (handle: string) => void;
}

const LAST_AGENT_KEY = "ajax.newTask.agent";
const LAST_REPO_KEY = "ajax.newTask.repo";

const AGENTS = [
  { value: "codex", label: "Codex" },
  { value: "claude", label: "Claude" },
  { value: "cursor", label: "Cursor" },
  { value: "opencode", label: "OpenCode" },
] as const;

function readPref(key: string): string | null {
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}

function initialRepo(repos: RepoSummary[], selectedProject: string | null): string {
  if (selectedProject && repos.some((r) => r.name === selectedProject)) return selectedProject;
  const remembered = readPref(LAST_REPO_KEY);
  if (remembered && repos.some((r) => r.name === remembered)) return remembered;
  return repos[0]?.name ?? "";
}

function initialAgent(): string {
  const remembered = readPref(LAST_AGENT_KEY);
  return AGENTS.some((option) => option.value === remembered) ? remembered! : "codex";
}

// ponytail: 14 lines instead of @radix-ui/react-radio-group. Radix was tried and
// discarded — inside the Dialog's focus scope its RovingFocusGroup never moved
// selection, which left the unselected agents unreachable by keyboard. Both arrow
// axes move because .agent-picker is a 2x2 grid.
function agentForArrowKey(current: string, key: string): string | null {
  const index = AGENTS.findIndex((option) => option.value === current);
  const delta =
    key === "ArrowRight" || key === "ArrowDown" ? 1
    : key === "ArrowLeft" || key === "ArrowUp" ? -1
    : 0;
  if (index < 0 || delta === 0) return null;
  return AGENTS[(index + delta + AGENTS.length) % AGENTS.length]!.value;
}

export default function NewTaskSheet({
  repos,
  selectedProject = null,
  onClose,
  onCockpit,
  onResult,
  onOpenTask,
}: Props) {
  const [repo, setRepo] = useState(() => initialRepo(repos, selectedProject));
  const [title, setTitle] = useState("");
  const [agent, setAgent] = useState(initialAgent);
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [dragOffset, setDragOffset] = useState(0);
  const sheetRef = useRef<HTMLDivElement>(null);
  const grabRef = useRef<HTMLDivElement>(null);

  // Focus restore is ours, not Radix's: modal DialogContent always preventDefaults
  // onCloseAutoFocus and focuses its triggerRef, and this sheet has no Dialog.Trigger,
  // so FocusScope would restore nothing. Radix still supplies the focus trap and
  // background aria-hidden. Focus lands on the container, never the repo <select> —
  // focusing a select pops the iOS picker the moment the sheet opens.
  useEffect(() => {
    const opener = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    sheetRef.current?.focus();
    return () => {
      opener?.focus();
    };
  }, []);

  useSheetDrag(grabRef, {
    onDismiss: () => onClose?.(),
    onOffset: setDragOffset,
  });

  function savePrefs() {
    try {
      localStorage.setItem(LAST_AGENT_KEY, agent);
      localStorage.setItem(LAST_REPO_KEY, repo);
    } catch {
      // Private mode / storage denied: defaults just won't stick.
    }
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!repo) {
      setError("Pick a repository first");
      return;
    }
    if (!title.trim()) {
      setError("Add a title");
      return;
    }
    setError(null);
    setSubmitting(true);
    try {
      const result = await startTask({
        repo,
        title: title.trim(),
        agent,
        request_id: requestId(),
      });
      if (result.response.cockpit) onCockpit?.(result.response.cockpit);
      if (!result.ok) {
        const message = result.error?.message ?? "Action failed";
        setError(message);
        onResult?.(message, result.response.output, true);
        return;
      }
      savePrefs();
      onResult?.("Task started", result.response.output, false);
      onOpenTask?.(startTaskHandle(repo, title));
      onClose?.();
    } catch {
      setError("Action failed — network error");
      onResult?.("Could not start task", null, true);
    } finally {
      setSubmitting(false);
    }
  }

  function handleBackdropClick(event: MouseEvent<HTMLDivElement>) {
    if (event.target === event.currentTarget) onClose?.();
  }

  return (
    <FullscreenLayer zIndex={50}>
      <Sheet
        open
        onOpenChange={(open) => {
          if (!open) onClose?.();
        }}
      >
        <SheetContent
          asChild
          aria-describedby={undefined}
          onOpenAutoFocus={(event) => {
            event.preventDefault();
          }}
        >
          {/* Backdrop dismissal only. This element IS the Radix content node, so a
              backdrop tap is *inside* it and onPointerDownOutside never fires; the
              target===currentTarget guard stays ours. Escape is Radix's, so there is
              deliberately no keyboard handler here. */}
          {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions -- backdrop click; Escape is Radix */}
          <div
            id="new-task-sheet"
            data-testid="new-task-sheet"
            role="dialog"
            aria-modal="true"
            tabIndex={-1}
            ref={sheetRef}
            onClick={handleBackdropClick}
          >
            <form
              className={`sheet-card${dragOffset > 0 ? " is-dragging" : ""}`}
              aria-label="New task"
              autoComplete="off"
              onSubmit={submit}
              style={{ transform: `translateY(${dragOffset}px)` }}
            >
              <div
                className="sheet-grab"
                aria-hidden="true"
                data-testid="sheet-grab"
                ref={grabRef}
              >
                <span className="sheet-grabber" />
              </div>
              {/* No id here: Slot lets child props win, so a hand-written id would
                  override Radix's titleId and leave aria-labelledby dangling. */}
              <SheetTitle asChild>
                <h2>New task</h2>
              </SheetTitle>

          <label htmlFor="new-task-repo">Repository</label>
          {repos.length ? (
            <select id="new-task-repo" value={repo} onChange={(e) => setRepo(e.target.value)}>
              {repos.map((option) => (
                <option key={option.name} value={option.name}>
                  {option.name}
                </option>
              ))}
            </select>
          ) : (
            <select id="new-task-repo" disabled>
              <option value="">No repositories configured</option>
            </select>
          )}

          <label htmlFor="new-task-title-input">Title</label>
          <input
            id="new-task-title-input"
            type="text"
            maxLength={80}
            enterKeyHint="go"
            placeholder="Short title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />

          <span className="field-label" id="new-task-agent">
            Agent
          </span>
          <div className="agent-picker" role="radiogroup" aria-labelledby="new-task-agent">
            {AGENTS.map((option) => (
              <button
                key={option.value}
                type="button"
                className={`agent-option${agent === option.value ? " is-selected" : ""}`}
                role="radio"
                aria-checked={agent === option.value}
                tabIndex={agent === option.value ? 0 : -1}
                onClick={() => setAgent(option.value)}
                onKeyDown={(event) => {
                  const next = agentForArrowKey(agent, event.key);
                  if (!next) return;
                  event.preventDefault();
                  setAgent(next);
                  const index = AGENTS.findIndex((entry) => entry.value === next);
                  const group = event.currentTarget.parentElement;
                  group?.querySelectorAll<HTMLButtonElement>(".agent-option")[index]?.focus();
                }}
              >
                {option.label}
              </button>
            ))}
          </div>

          {error ? <p className="sheet-error">{error}</p> : null}

          <div className="sheet-actions">
            <Button type="button" variant="secondary" onClick={() => onClose?.()}>
              Cancel
            </Button>
            <Button type="submit" variant="default" disabled={submitting}>
              Start
            </Button>
            </div>
          </form>
        </div>
        </SheetContent>
      </Sheet>
    </FullscreenLayer>
  );
}

// crates/ajax-web/web/src/components/NewTaskSheet.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import type { BrowserCockpitView, RepoSummary } from "../types";
  import { requestId, startTask } from "../api";
  import { startTaskHandle } from "../taskSlug";
  import { sheetDrag } from "../gestures/sheetDragAction";
  import FullscreenLayer from "./FullscreenLayer.svelte";

  interface Props {
    repos: RepoSummary[];
    selectedProject?: string | null;
    onClose?: () => void;
    onCockpit?: (cockpit: BrowserCockpitView) => void;
    onResult?: (message: string, output: string | null | undefined, isError: boolean) => void;
    onOpenTask?: (handle: string) => void;
  }

  let { repos, selectedProject = null, onClose, onCockpit, onResult, onOpenTask }: Props = $props();

  // Remembered form defaults — a browser-side convenience only, never task truth.
  const LAST_AGENT_KEY = "ajax.newTask.agent";
  const LAST_REPO_KEY = "ajax.newTask.repo";

  function readPref(key: string): string | null {
    try {
      return localStorage.getItem(key);
    } catch {
      return null;
    }
  }

  function savePrefs() {
    try {
      localStorage.setItem(LAST_AGENT_KEY, agent);
      localStorage.setItem(LAST_REPO_KEY, repo);
    } catch {
      // Private mode / storage denied: defaults just won't stick.
    }
  }

  const AGENTS = [
    { value: "codex", label: "Codex" },
    { value: "claude", label: "Claude" },
    { value: "cursor", label: "Cursor" },
    { value: "opencode", label: "OpenCode" },
  ];

  // Capture the initial repo once; the form then owns the selection locally.
  // Priority: the project the user is looking at, then the last-used repo.
  let repo = $state(
    untrack(() => {
      if (selectedProject && repos.some((r) => r.name === selectedProject)) return selectedProject;
      const remembered = readPref(LAST_REPO_KEY);
      if (remembered && repos.some((r) => r.name === remembered)) return remembered;
      return repos[0]?.name ?? "";
    }),
  );
  let title = $state("");
  let agent = $state(
    untrack(() => {
      const remembered = readPref(LAST_AGENT_KEY);
      return AGENTS.some((option) => option.value === remembered) ? remembered! : "codex";
    }),
  );
  let error = $state<string | null>(null);
  let submitting = $state(false);
  let dragOffset = $state(0);
  let sheetEl = $state<HTMLDivElement | null>(null);

  $effect(() => {
    sheetEl?.focus();
  });

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    if (!repo) {
      error = "Pick a repository first";
      return;
    }
    if (!title.trim()) {
      error = "Add a title";
      return;
    }
    error = null;
    submitting = true;
    try {
      const result = await startTask({
        repo,
        title: title.trim(),
        agent,
        request_id: requestId(),
      });
      if (result.response.cockpit) onCockpit?.(result.response.cockpit);
      if (!result.ok) {
        error = result.error?.message ?? "Action failed";
        onResult?.(error, result.response.output, true);
        return;
      }
      savePrefs();
      onResult?.("Task started", result.response.output, false);
      onOpenTask?.(startTaskHandle(repo, title));
      onClose?.();
    } catch {
      error = "Action failed — network error";
      onResult?.("Could not start task", null, true);
    } finally {
      submitting = false;
    }
  }
</script>

<FullscreenLayer zIndex={50}>
<div
  id="new-task-sheet"
  data-testid="new-task-sheet"
  role="dialog"
  aria-modal="true"
  aria-labelledby="new-task-title"
  tabindex="-1"
  bind:this={sheetEl}
  onclick={(event) => {
    if (event.target === event.currentTarget) onClose?.();
  }}
  onkeydown={(event) => {
    if (event.key === "Escape") onClose?.();
  }}
>
  <form
    class="sheet-card"
    autocomplete="off"
    onsubmit={submit}
    style="transform: translateY({dragOffset}px)"
    class:is-dragging={dragOffset > 0}
  >
    <div
      class="sheet-grab"
      aria-hidden="true"
      use:sheetDrag={{ onDismiss: () => onClose?.(), onOffset: (offset) => (dragOffset = offset) }}
    >
      <span class="sheet-grabber"></span>
    </div>
    <h2 id="new-task-title">New task</h2>

    <label for="new-task-repo">Repository</label>
    {#if repos.length}
      <select id="new-task-repo" bind:value={repo}>
        {#each repos as option (option.name)}
          <option value={option.name}>{option.name}</option>
        {/each}
      </select>
    {:else}
      <select id="new-task-repo" disabled>
        <option value="">No repositories configured</option>
      </select>
    {/if}

    <label for="new-task-title-input">Title</label>
    <input
      id="new-task-title-input"
      type="text"
      maxlength="80"
      enterkeyhint="go"
      placeholder="Short title"
      bind:value={title}
    />

    <span class="field-label" id="new-task-agent">Agent</span>
    <div class="agent-picker" role="radiogroup" aria-labelledby="new-task-agent">
      {#each AGENTS as option (option.value)}
        <button
          type="button"
          class="agent-option"
          class:is-selected={agent === option.value}
          role="radio"
          aria-checked={agent === option.value}
          onclick={() => (agent = option.value)}>{option.label}</button>
      {/each}
    </div>

    {#if error}
      <p class="sheet-error">{error}</p>
    {/if}

    <div class="sheet-actions">
      <button type="button" class="pill" onclick={() => onClose?.()}>Cancel</button>
      <button type="submit" class="pill is-primary" disabled={submitting}>Start</button>
    </div>
  </form>
</div>
</FullscreenLayer>

<style>
  /* NEW TASK SHEET — bottom-rising modal inside FullscreenLayer's app band. */
  #new-task-sheet {
    flex: 1 1 auto;
    min-height: 0;
    display: flex;
    align-items: flex-end;
    justify-content: center;
    padding: 20px;
    background: rgba(0, 0, 0, 0.6);
    overflow: hidden;
    box-sizing: border-box;
  }

  .sheet-card {
    background: var(--paper-raised);
    border: 1px solid var(--rule-strong);
    border-radius: var(--radius);
    padding: 22px;
    width: min(440px, 100%);
    max-height: calc(100% - 40px);
    margin-bottom: max(8px, env(safe-area-inset-bottom));
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
    animation: sheet-rise 220ms var(--ease-spring);
  }

  /* Spring the card back to rest when a drag is released below threshold. */
  .sheet-card:not(.is-dragging) {
    transition: transform 220ms var(--ease-spring);
  }

  /* Grabber — the touch target for drag-to-dismiss. */
  .sheet-grab {
    display: flex;
    justify-content: center;
    padding: 4px 0 12px;
    margin: -8px 0 0;
    cursor: grab;
    touch-action: none;
  }

  .sheet-grabber {
    width: 36px;
    height: 4px;
    border-radius: 999px;
    background: var(--rule-strong);
  }

  .sheet-card h2 {
    margin: 0 0 16px;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: var(--label-tracking);
    text-transform: uppercase;
    color: var(--ink-muted);
  }

  .sheet-card label,
  .sheet-card .field-label {
    display: block;
    margin-top: 14px;
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--ink-muted);
  }

  .sheet-card input,
  .sheet-card select {
    width: 100%;
    margin-top: 5px;
    padding: 10px 12px;
    font-size: 16px;
    background: var(--paper);
    color: var(--ink);
    border: 1px solid var(--rule-strong);
    border-radius: var(--radius-sm);
  }

  .sheet-card input:focus,
  .sheet-card select:focus {
    outline: none;
    border-color: var(--accent-bright);
  }

  /* Segmented agent picker — all choices visible, one tap, no dropdown scroll. */
  .agent-picker {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 6px;
    margin-top: 6px;
  }

  .agent-option {
    padding: 10px 12px;
    font-size: 14px;
    font-weight: 600;
    background: var(--paper);
    color: var(--ink-muted);
    border: 1px solid var(--rule-strong);
    border-radius: var(--radius-sm);
  }

  .agent-option.is-selected {
    background: var(--accent-deep);
    border-color: var(--accent);
    color: var(--ink);
  }

  .agent-option:focus-visible {
    outline: none;
    border-color: var(--accent-bright);
  }

  .sheet-actions {
    display: flex;
    justify-content: flex-end;
    gap: 10px;
    margin-top: 22px;
  }

  .sheet-error {
    margin: 12px 0 0;
    color: var(--danger);
    font-size: 12px;
  }

  @keyframes sheet-rise {
    from { opacity: 0; transform: translateY(16px); }
    to { opacity: 1; transform: translateY(0); }
  }

  @media (max-width: 380px) {
    .sheet-card { padding: 18px; }
  }
</style>
